language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
cache:
  apt: true
  pip: false
install:
- pip install --upgrade django coverage pytest unittest2 pytest-cov coveralls
- python setup.py clean --all
- python setup.py install
- python setup.py clean --all
script:
- py.test --cov=pg_utils
after_success:
- coveralls
